"""The scorecard's two copies must be one measurement.

`tools/scorecard.py --emit` writes the benchmark table to two places from one run:
`docs/scorecard.md` wholesale, and the block between the scorecard markers in
`README.md`. The whole point of the tool is that every quoted number describes the same
animal on the same day ("a crawling speed from day two beside a frequency from day
nine"), and these tests extend that property to the documents: a hand edit to either
copy — a helpful tweak to the README table, a stray reformat of the doc — makes them
disagree, and disagreement fails here, in the unit shard, in milliseconds.

Deliberately NOT asserted: freshness. Every legitimate model change moves behavioural
numbers, so a gate that re-measured on every commit would turn each real improvement
into a mandatory repin plus fifteen minutes of CI — the grazing-pin lesson, applied.
The emitted block carries its date and commit so staleness is visible; regeneration is
`tools/scorecard.py --emit` or the dispatch-only `scorecard` workflow.
"""

from __future__ import annotations

import os
import re

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
BEGIN = "<!-- scorecard:begin (generated by tools/scorecard.py --emit; do not hand-edit) -->"
END = "<!-- scorecard:end -->"


def _block(path):
    with open(os.path.join(ROOT, path)) as f:
        text = f.read()
    a, b = text.find(BEGIN), text.find(END)
    assert a >= 0 and b > a, "%s has lost its scorecard markers" % path
    return text[a:b + len(END)]


def test_readme_and_scorecard_doc_carry_the_same_table():
    assert _block("README.md") == _block("docs/scorecard.md"), (
        "README.md and docs/scorecard.md disagree about the scorecard: one of them was "
        "edited by hand. Regenerate BOTH from one run with `tools/scorecard.py --emit` "
        "(or dispatch the scorecard workflow); do not edit either copy directly.")


def test_the_emitted_block_says_when_and_from_what_it_was_measured():
    """Freshness is not gated, so it must at least be visible."""
    block = _block("README.md")
    assert re.search(r"Measured \d{4}-\d{2}-\d{2} at `[0-9a-f]+`", block), (
        "the scorecard block carries no measurement date/commit stamp; without one, "
        "staleness has no way to be seen")


def test_the_doc_declares_itself_generated():
    with open(os.path.join(ROOT, "docs", "scorecard.md")) as f:
        head = f.read(400)
    assert "GENERATED" in head and "--emit" in head, (
        "docs/scorecard.md no longer says it is generated; the next editor will "
        "hand-edit it and the consistency test will read as the mystery instead of "
        "the explanation")
