/* Check the WebAssembly runtime against the Python, step for step.
 *
 * Both sides read their setup out of web/worm.model, so a disagreement here is in the
 * stepping and nowhere else. The mechanics are checked first because they are the piece
 * most likely to be got wrong -- a 50x50 drag metric assembled from masked matrix
 * products, then solved -- and the piece where being wrong is least obvious downstream,
 * since slightly wrong drag still produces a worm-shaped thing that wriggles.
 */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

// fileURLToPath, not .pathname. A file URL's pathname on Windows is "/C:/src/wasm/", and
// joining that onto anything gives "C:\C:\src\...", which is not a path anywhere.
const ROOT = fileURLToPath(new URL('..', import.meta.url));
const at = (...p) => path.join(ROOT, ...p);

const inputs = [
  {
    path: at('web', 'worm.wasm'),
    display: 'web/worm.wasm',
    command: 'cd wasm && npx asc assembly/index.ts --target release',
  },
  {
    path: at('web', 'worm.model'),
    display: 'web/worm.model',
    command: 'PYTHONPATH=. python tools/export_model.py',
  },
  {
    path: at('web', 'conform.json'),
    display: 'web/conform.json',
    command: 'PYTHONPATH=. python tools/conform.py > web/conform.json',
  },
];
const missing = inputs.filter(input => !fs.existsSync(input.path));
if (missing.length) {
  for (const input of missing) {
    console.error(`Missing ${input.display}; generate it with: ${input.command}`);
  }
  process.exit(2);
}

const modelMtime = fs.statSync(at('web', 'worm.model')).mtimeMs;
const referenceMtime = fs.statSync(at('web', 'conform.json')).mtimeMs;
if (referenceMtime < modelMtime) {
  console.warn(
    'Warning: web/conform.json is older than web/worm.model; regenerate it with: ' +
    'PYTHONPATH=. python tools/conform.py > web/conform.json',
  );
}

const wasmBuf = fs.readFileSync(at('web', 'worm.wasm'));
const modelBuf = fs.readFileSync(at('web', 'worm.model'));
const ref = JSON.parse(fs.readFileSync(at('web', 'conform.json'), 'utf8'));

// --- model file: 'WORM' + version, u32 header length, JSON header, payload ------------
const dv = new DataView(modelBuf.buffer, modelBuf.byteOffset, modelBuf.byteLength);
const headLen = dv.getUint32(8, true);
const meta = JSON.parse(new TextDecoder().decode(modelBuf.subarray(12, 12 + headLen)));
const payload = modelBuf.subarray(12 + headLen);

const mod = new WebAssembly.Module(wasmBuf);
const inst = new WebAssembly.Instance(mod, {
  env: { abort(msg, file, line, col) { throw new Error(`wasm abort at ${line}:${col}`); } },
});
const E = inst.exports;

// The payload holds f64 arrays, so it has to start on an 8-byte boundary or the views
// the runtime builds over it are misaligned.
const raw = E.alloc(payload.length + 8);
const ptr = (raw + 7) & ~7;
new Uint8Array(E.memory.buffer).set(payload, ptr);
E.setPayload(ptr);
E.initWorld();

const F64 = () => new Float64Array(E.memory.buffer);

// Gene slot numbering is generated by tools/export_model.py and recorded in the model
// header, so neither side keeps its own copy of the list.
const G_MOD1 = meta.genes.indexOf('mod_serotonin_mod1');
if (G_MOD1 < 0) { console.error('the model declares no mod_serotonin_mod1 gene'); process.exit(1); }

// --- the mechanics ---------------------------------------------------------------------
const c = ref.body;
const w = E.createWorm(0, 0.0, 0.0, 0.0);
c.moment.forEach((v, j) => E.setMoment(w, j, v));

let worstXY = 0, worstK = 0, prev = 0;
for (const f of c.frames) {
  E.stepBodyOnly(w, c.dt, f.step - prev);
  prev = f.step;
  const nx = F64().subarray(E.ptrNodesX(w) >> 3, (E.ptrNodesX(w) >> 3) + f.x.length);
  const ny = F64().subarray(E.ptrNodesY(w) >> 3, (E.ptrNodesY(w) >> 3) + f.y.length);
  const kk = F64().subarray(E.ptrKappa(w) >> 3, (E.ptrKappa(w) >> 3) + f.kappa.length);
  for (let i = 0; i < f.x.length; i++) {
    worstXY = Math.max(worstXY, Math.abs(nx[i] - f.x[i]), Math.abs(ny[i] - f.y[i]));
  }
  for (let i = 0; i < f.kappa.length; i++) {
    worstK = Math.max(worstK, Math.abs(kk[i] - f.kappa[i]));
  }
}

const last = c.frames[c.frames.length - 1];
const span = Math.hypot(last.x[0] - last.x[last.x.length - 1],
                        last.y[0] - last.y[last.y.length - 1]);
console.log(`MECHANICS -- prescribed moment, ${c.steps} steps, no biology, no noise`);
console.log(`  worst node disagreement       ${worstXY.toExponential(3)} mm` +
            `   (body spans ${span.toFixed(3)} mm)`);
console.log(`  worst curvature disagreement  ${worstK.toExponential(3)} /mm`);
const mechOk = worstXY < 1e-9 && worstK < 1e-7;
console.log(mechOk ? '  PASS' : '  FAIL');

// --- the whole loop --------------------------------------------------------------------
// The same plate the Python built. This has to be kept in step with conform.py by hand,
// and it is worth the nuisance: the first version of this test ran both sides on an empty
// dish, where every sensory field reads zero -- so it passed while the WASM's food field
// had an exponential skirt the Python's does not, and an animal seven millimetres outside
// a five millimetre lawn thought it was standing on one.
const fc = ref.full;
E.setNoise(0);
E.addFood(-6.0, 4.0, 5.0, 1.0, 1.0, 9.0);
E.addRepellent(7.0, -3.0, 0.9, 5.0);
E.addFood(0.0, 0.0, 3.0, 1.0, 0.6, 6.0);   // food under the animal; see conform.py
const w2 = E.createWorm(0, 0.0, 0.0, 0.0);
let wXY = 0, wV = 0, wT = 0, gateBad = 0, wEgl = 0, wPh = 0;
// Distinct values seen per pharynx quantity. A comparison over a constant is not a
// comparison: three of egg-laying's four variables were once compared on a plate the
// animal never ate from, and agreed perfectly while covering nothing.
const phSeen = [new Set(), new Set(), new Set()];
prev = 0;
for (const f of fc.frames) {
  E.step(w2, f.step - prev);
  prev = f.step;
  const nx = F64().subarray(E.ptrNodesX(w2) >> 3, (E.ptrNodesX(w2) >> 3) + f.x.length);
  const ny = F64().subarray(E.ptrNodesY(w2) >> 3, (E.ptrNodesY(w2) >> 3) + f.y.length);
  const vv = F64().subarray(E.ptrV(w2) >> 3, (E.ptrV(w2) >> 3) + f.V.length);
  const tt = F64().subarray(E.ptrTension(w2) >> 3, (E.ptrTension(w2) >> 3) + f.tension.length);
  for (let i = 0; i < f.x.length; i++)
    wXY = Math.max(wXY, Math.abs(nx[i] - f.x[i]), Math.abs(ny[i] - f.y[i]));
  for (let i = 0; i < f.V.length; i++) wV = Math.max(wV, Math.abs(vv[i] - f.V[i]));
  for (let i = 0; i < f.tension.length; i++) wT = Math.max(wT, Math.abs(tt[i] - f.tension[i]));
  if (E.getGateForward(w2) !== f.gate) gateBad++;
  // No `if (f.egl)`. A missing field is a broken reference, not a field with nothing to
  // say, and guarding on its presence is how this check spent its whole life printing a
  // perfect 0.000e+0 while comparing nothing: the exporter-side edit that was supposed to
  // emit `egl` silently matched no text and never applied, and the guard turned that into
  // a pass. Absent data fails here now.
  if (!f.egl) { console.error('  reference frame has no `egl` -- regenerate it'); process.exit(1); }
  const got = [E.getVulvalMuscle(w2), E.getEggsHeld(w2), E.getEglResource(w2), E.getEggsLaid(w2)];
  for (let i = 0; i < 4; i++) wEgl = Math.max(wEgl, Math.abs(got[i] - f.egl[i]));
  // Feeding, on the same terms: absent data is a broken reference, not a pass.
  if (!f.ph) { console.error('  reference frame has no `ph` -- regenerate it'); process.exit(1); }
  const ph = [E.getLumen(w2), E.getIngested(w2), E.getEaten(w2)];
  for (let i = 0; i < 3; i++) wPh = Math.max(wPh, Math.abs(ph[i] - f.ph[i]));
  phSeen.forEach((set, i) => set.add(f.ph[i]));
}
console.log(`\nWHOLE LOOP -- neurons, muscle, senses, body; ${fc.steps} steps, noise off`);
console.log(`  worst node disagreement       ${wXY.toExponential(3)} mm`);
console.log(`  worst membrane potential      ${wV.toExponential(3)} mV`);
console.log(`  worst muscle tension          ${wT.toExponential(3)}`);
console.log(`  direction gate disagreed on   ${gateBad} of ${fc.frames.length} samples`);
console.log(`  worst egg-laying state        ${wEgl.toExponential(3)}   (vm, held, resource, laid)`);
console.log(`  worst feeding state           ${wPh.toExponential(3)}   (lumen, ingested, eaten)`);
const phNames = ['lumen', 'ingested', 'eaten'];
const phFlat = phSeen.map((set, i) => (set.size > 1 ? null : phNames[i])).filter(Boolean);
if (phFlat.length) {
  console.log(`  NOT COVERED: ${phFlat.join(', ')} never changed over the run`);
}
const fullOk = wXY < 1e-6 && wV < 1e-6 && wT < 1e-8 && gateBad === 0 && wEgl < 1e-8
  && wPh < 1e-8 && phFlat.length === 0;
console.log(fullOk ? '  PASS' : '  FAIL');

// --- with cells removed -----------------------------------------------------------------
// Ablation is the largest piece of this runtime that nothing checked. It has its own branch
// in eleven places -- the gap accumulation skips dead neighbours, gapTot is rebuilt,
// synaptic release is zeroed, the dead cell's voltage is pinned at leak after the solve,
// and activation() reports zero so a cell that is not present cannot vote in the direction
// gate. None of it ran here until now, and an ablation that is only mostly applied still
// produces a worm-shaped thing that wriggles.
const ac = ref.ablated;
E.resetWorld();
E.clearWorms();
E.setNoise(0);
E.addFood(-6.0, 4.0, 5.0, 1.0, 1.0, 9.0);
E.addRepellent(7.0, -3.0, 0.9, 5.0);
const w3 = E.createWorm(0, 0.0, 0.0, 0.0);

// Warm up first: the cells have to be *alive and running* when they are killed, or the
// code that clears their live state is never exercised. See conform.py.
E.step(w3, ac.warm);

// setAblated takes a pointer to i32 indices, so the list has to go into linear memory.
const idxPtr = E.alloc(ac.ablated.length * 4);
new Int32Array(E.memory.buffer, idxPtr, ac.ablated.length).set(ac.ablated);
E.setAblated(w3, idxPtr, ac.ablated.length);

// Cheapest possible check first, and the one whose failure explains all the others.
let aliveBad = 0;
for (const i of ac.ablated) if (E.isAlive(w3, i) !== 0) aliveBad++;

let aXY = 0, aV = 0, aT = 0, aAct = 0, aGate = 0, deadNoisy = 0;
prev = 0;
for (const f of ac.frames) {
  E.step(w3, f.step - prev);
  prev = f.step;
  const nx = F64().subarray(E.ptrNodesX(w3) >> 3, (E.ptrNodesX(w3) >> 3) + f.x.length);
  const ny = F64().subarray(E.ptrNodesY(w3) >> 3, (E.ptrNodesY(w3) >> 3) + f.y.length);
  const vv = F64().subarray(E.ptrV(w3) >> 3, (E.ptrV(w3) >> 3) + f.V.length);
  const aa = F64().subarray(E.ptrAct(w3) >> 3, (E.ptrAct(w3) >> 3) + f.act.length);
  const tt = F64().subarray(E.ptrTension(w3) >> 3, (E.ptrTension(w3) >> 3) + f.tension.length);
  for (let i = 0; i < f.x.length; i++)
    aXY = Math.max(aXY, Math.abs(nx[i] - f.x[i]), Math.abs(ny[i] - f.y[i]));
  for (let i = 0; i < f.V.length; i++) aV = Math.max(aV, Math.abs(vv[i] - f.V[i]));
  for (let i = 0; i < f.act.length; i++) aAct = Math.max(aAct, Math.abs(aa[i] - f.act[i]));
  for (let i = 0; i < f.tension.length; i++) aT = Math.max(aT, Math.abs(tt[i] - f.tension[i]));
  if (E.getGateForward(w3) !== f.gate) aGate++;
  // A dead cell must be silent, not merely disagreeing quietly: pinned at its leak
  // potential and contributing nothing to the direction gate.
  for (const i of ac.ablated) if (aa[i] !== 0.0) deadNoisy++;
}

console.log(`\nABLATED -- ${ac.names.join(', ')}; ${ac.steps} steps, noise off`);
console.log(`  cells reported dead           ${ac.ablated.length - aliveBad} of ${ac.ablated.length}`);
console.log(`  worst node disagreement       ${aXY.toExponential(3)} mm`);
console.log(`  worst membrane potential      ${aV.toExponential(3)} mV`);
console.log(`  worst activation              ${aAct.toExponential(3)}`);
console.log(`  worst muscle tension          ${aT.toExponential(3)}`);
console.log(`  direction gate disagreed on   ${aGate} of ${ac.frames.length} samples`);
console.log(`  ablated cells still active    ${deadNoisy}`);
const ablOk = aliveBad === 0 && deadNoisy === 0 && aXY < 1e-6 && aV < 1e-6
           && aAct < 1e-8 && aT < 1e-8 && aGate === 0;
console.log(ablOk ? '  PASS' : '  FAIL');

/* --- MOD-1, the one pathway that was shipped and never wired up -------------------------
 *
 * The serotonin-gated chloride conductance exists in worm/modulators.py, is exported into
 * the model file, is named in the roadmap as a parameter worth evolving -- and had zero
 * occurrences in the runtime. Nothing noticed, because the shipped coefficient is 0.0 and
 * a term multiplied by zero is indistinguishable from a term that is not there.
 *
 * So this case runs both sides at the coefficient params.py documents, 0.30. The Python
 * reference is built with `serotonin_mod1=0.30`; the runtime is given the same number as a
 * gene, which it can be because the coefficient is no longer baked into the payload --
 * `mod1_unit` carries the target set's resting conductance and the gene scales it. */
const mc = ref.mod1;
if (!mc) { console.error('reference has no `mod1` case -- regenerate it'); process.exit(1); }
E.resetWorld();
E.clearWorms();
E.setNoise(0);
E.addFood(-6.0, 4.0, 5.0, 1.0, 1.0, 9.0);
E.addRepellent(7.0, -3.0, 0.9, 5.0);
E.addFood(0.0, 0.0, 3.0, 1.0, 0.6, 6.0);
const w4 = E.createWorm(0, 0.0, 0.0, 0.0);
E.setGene(w4, G_MOD1, 0.30);
let mXY = 0, mV = 0, mGate = 0;
prev = 0;
for (const f of mc.frames) {
  E.step(w4, f.step - prev);
  prev = f.step;
  const nx = F64().subarray(E.ptrNodesX(w4) >> 3, (E.ptrNodesX(w4) >> 3) + f.x.length);
  const ny = F64().subarray(E.ptrNodesY(w4) >> 3, (E.ptrNodesY(w4) >> 3) + f.y.length);
  const vv = F64().subarray(E.ptrV(w4) >> 3, (E.ptrV(w4) >> 3) + f.V.length);
  for (let i = 0; i < f.x.length; i++)
    mXY = Math.max(mXY, Math.abs(nx[i] - f.x[i]), Math.abs(ny[i] - f.y[i]));
  for (let i = 0; i < f.V.length; i++) mV = Math.max(mV, Math.abs(vv[i] - f.V[i]));
  if (E.getGateForward(w4) !== f.gate) mGate++;
}
/* And the case has to be *different* from the one with the channel shut, or it is another
 * comparison over a term that never moved. Same seed, same plate, coefficient 0 vs 0.30. */
E.resetWorld(); E.clearWorms(); E.setNoise(0);
E.addFood(-6.0, 4.0, 5.0, 1.0, 1.0, 9.0);
E.addRepellent(7.0, -3.0, 0.9, 5.0);
E.addFood(0.0, 0.0, 3.0, 1.0, 0.6, 6.0);
const wOff = E.createWorm(0, 0.0, 0.0, 0.0);
E.step(wOff, mc.steps);
const offV = Array.from(F64().subarray(E.ptrV(wOff) >> 3, (E.ptrV(wOff) >> 3) + 302));
const lastV = mc.frames[mc.frames.length - 1].V;
let mod1Effect = 0;
for (let i = 0; i < 302; i++) mod1Effect = Math.max(mod1Effect, Math.abs(offV[i] - lastV[i]));

console.log(`\nMOD-1 -- serotonin-gated chloride at 0.30, ${mc.steps} steps, noise off`);
console.log(`  worst node disagreement       ${mXY.toExponential(3)} mm`);
console.log(`  worst membrane potential      ${mV.toExponential(3)} mV`);
console.log(`  direction gate disagreed on   ${mGate} of ${mc.frames.length} samples`);
console.log(`  channel actually did something ${mod1Effect.toExponential(3)} mV against the same animal with it shut`);
const mod1Ok = mXY < 1e-6 && mV < 1e-6 && mGate === 0 && mod1Effect > 1e-3;
console.log(mod1Ok ? '  PASS' : '  FAIL');

// --- the path the browser actually runs ----------------------------------------------
// Everything above drives `step(w, n)`. The viewer drives `stepAll(n)`, which is a
// different function with its own loop and its own world advance, and nothing had ever
// compared them: a defect in the multi-worm path would have been invisible to every check
// here while being the only path a visitor ever executes.
//
// With a single animal the two must be identical step for step, which makes this exact
// rather than statistical. It is a cheap invariant and it covers the ordering -- one world
// advance per step, not one per animal per step, which is the mistake the shape invites.
function trajectory(useStepAll) {
  E.resetWorld();
  E.clearWorms();
  E.setNoise(0);
  E.addFood(0.0, 0.0, 3.0, 1.0, 0.6, 6.0);
  const w = E.createWorm(0, 0.0, 0.0, 0.0);
  for (let i = 0; i < 600; i++) useStepAll ? E.stepAll(1) : E.step(w, 1);
  const n = F64().subarray(E.ptrNodesX(w) >> 3, (E.ptrNodesX(w) >> 3) + 49);
  const v = F64().subarray(E.ptrV(w) >> 3, (E.ptrV(w) >> 3) + 302);
  return { nodes: Array.from(n), V: Array.from(v), eggs: E.getEggsHeld(w) };
}
const viaStep = trajectory(false);
const viaAll = trajectory(true);
let wAll = 0;
for (let i = 0; i < viaStep.nodes.length; i++) wAll = Math.max(wAll, Math.abs(viaStep.nodes[i] - viaAll.nodes[i]));
for (let i = 0; i < viaStep.V.length; i++) wAll = Math.max(wAll, Math.abs(viaStep.V[i] - viaAll.V[i]));
wAll = Math.max(wAll, Math.abs(viaStep.eggs - viaAll.eggs));
console.log(`\nSTEP PATHS -- stepAll(1) against step(w,1), one animal, 600 steps`);
console.log(`  worst disagreement            ${wAll.toExponential(3)}`);
const allOk = wAll === 0;
console.log(allOk ? '  PASS' : '  FAIL');

const ok = mechOk && fullOk && ablOk && mod1Ok && allOk;
console.log(ok ? '\nThe port reproduces the Python model.'
               : '\nThe port does NOT reproduce the Python model.');
process.exit(ok ? 0 : 1);
